import create from "zustand";
import { persist } from "zustand/middleware";


const usePokedex = create(
    persist(
        (set, get) => ({
            appConfig: {
                home: {
                    app: "Pokeapp with Next",
                    title: "Catálogo",
                    description: "Generated by create next app",
                    loadButton: "Load more"
                }
            },
            setAppConfig: (newConfig: object) => {
                set(state => {
                    state.appConfig = newConfig
                })
            },
            pokemon: {},
            setSelectedPokemon: (params: object) => {
                set(state => ({
                    ...state,
                    pokemon: params
                }));
            },
            currentPage: 20,
            setCurrentPage: (params: number) => {
                set(state => ({
                    ...state,
                    currentPage: params
                }));
            },
            loading: false,
            setLoading: (params: boolean) => {
                set(state => ({
                    ...state,
                    loading: params
                }));
            },
            clearCurrentPage: () => {
                set(state => ({
                    ...state,
                    currentPage: 20
                }));
            }

        }),
        {name: "pokedex"}
    ),
)

export default usePokedex;