import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CardList from '../components/CardList'
import CardItem from '../components/CardItem'
import useData from '../hooks/useData'
//import store
import usePokedex from '../store/store'

const Home: NextPage = () => {
    //call from store current page
    const currentPage = usePokedex((state:any) => state.currentPage)
    const setCurrentPage = usePokedex((state: any) => state.setCurrentPage)
    
    const { data, error } = useData(`https://pokeapi.co/api/v2/pokemon/?limit=${currentPage}`, '0')    
    
    if(error) return <div>Error...</div>
    if(!data) return <div>Loading...</div>

    //onclick load more button lazy loading
    const lazyLoad = () => {
        setCurrentPage(currentPage + 20)
    }

    return (
    <div className={styles.container}>
        <Head>
        <title>Pokedex app with Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>  
            <h1 className={styles.title}>Catálogo</h1>
            <CardList >
                {
                    data.results.map((pokemon: any) => (
                        <CardItem key={pokemon.name} pokemon={pokemon} />
                    ))
                }
            </CardList>
            <div>
                <button type='button' onClick={ lazyLoad }>Load more</button>
            </div>
        </main>
    </div>
    )
}

export default Home
